# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hy < Formula
  desc "CLI for Hypewell Studio"
  homepage "https://hypewell.ai"
  version "0.2.0"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hypewell-ai/hy/releases/download/v0.2.0/hy_0.2.0_darwin_amd64.tar.gz"
      sha256 "6331cbf55ace57f58651a749dd85bd9ed819067c11da6c3c72e5060d32c5bf6c"

      def install
        bin.install "hy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hypewell-ai/hy/releases/download/v0.2.0/hy_0.2.0_darwin_arm64.tar.gz"
      sha256 "6138733b65a24780813de795f07ed02a3ee5f567ffe8ed490d8dc340b008d5a2"

      def install
        bin.install "hy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hypewell-ai/hy/releases/download/v0.2.0/hy_0.2.0_linux_amd64.tar.gz"
      sha256 "da6ad7fae0c8ecbecac83c593b751e76747ce19cacb85047cf89cf75f4bd421f"
      def install
        bin.install "hy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hypewell-ai/hy/releases/download/v0.2.0/hy_0.2.0_linux_arm64.tar.gz"
      sha256 "7dacdda2b1a265e9325db04c40044ab6202643d04b6210ca5aaf99ba45ccd614"
      def install
        bin.install "hy"
      end
    end
  end

  test do
    system "#{bin}/hy", "version"
  end
end
