# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hy < Formula
  desc "CLI for Hypewell Studio"
  homepage "https://hypewell.ai"
  version "0.2.1"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hypewell-ai/hy/releases/download/v0.2.1/hy_0.2.1_darwin_amd64.tar.gz"
      sha256 "040520e6a692e3e113eb4aadeb2736066f24d65b3d08d6f8c5b51a53951dd859"

      def install
        bin.install "hy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hypewell-ai/hy/releases/download/v0.2.1/hy_0.2.1_darwin_arm64.tar.gz"
      sha256 "067c2f5ae7e171b34628924ecf807e7f0bd48031acb2f95ef582557e6c254e59"

      def install
        bin.install "hy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hypewell-ai/hy/releases/download/v0.2.1/hy_0.2.1_linux_amd64.tar.gz"
      sha256 "ce61490ba544b3f767c797afe11eb23674ef651d006b652d98d491f61c56c5ed"
      def install
        bin.install "hy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hypewell-ai/hy/releases/download/v0.2.1/hy_0.2.1_linux_arm64.tar.gz"
      sha256 "7a764a30c086ed70df8dde44b3fdba6b798041baeaabc9ae37b3156d497eae06"
      def install
        bin.install "hy"
      end
    end
  end

  test do
    system "#{bin}/hy", "version"
  end
end
