# This formula is auto-generated by GoReleaser.
# Manual edits will be overwritten on the next release.
#
# To install: brew install hypewell-ai/tap/hy

class Hy < Formula
  desc "CLI for Hypewell Studio"
  homepage "https://hypewell.ai"
  license "Proprietary"

  # Placeholder - GoReleaser will update this on release
  version "0.0.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/hypewell-ai/hy/releases/download/v#{version}/hy_#{version}_darwin_arm64.tar.gz"
      sha256 "PLACEHOLDER"
    else
      url "https://github.com/hypewell-ai/hy/releases/download/v#{version}/hy_#{version}_darwin_amd64.tar.gz"
      sha256 "PLACEHOLDER"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/hypewell-ai/hy/releases/download/v#{version}/hy_#{version}_linux_arm64.tar.gz"
      sha256 "PLACEHOLDER"
    else
      url "https://github.com/hypewell-ai/hy/releases/download/v#{version}/hy_#{version}_linux_amd64.tar.gz"
      sha256 "PLACEHOLDER"
    end
  end

  def install
    bin.install "hy"
  end

  test do
    system "#{bin}/hy", "version"
  end
end
